title: "Hello World!"
author: "Nha Do"
description: "University of California, Los Angeles (UCLA)"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "My CV", url: "https://nhado401.github.io/files/MyCV.pdf}
  - {title: "Work Experience"}
  - {title: "Research Experience", file: "Research Experience.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, url: "mailto:nhado401@gmail.com"}
  - {title: Github, url: "https://github.com/nhado401"}
  - {title: "Personal Blog", url: "https://nhavtdo.wordpress.com/"} 

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
