title: "Nha Do"
author: "Nha Do"
description: "UCLA --> AT&T Corp."
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "Resume", url: "https://nhado401.github.io/files/NhaDo_Resume.pdf"}
  - {title: "Projects", file: "Project.md"}
  - {title: "Experiences", file: "Experience.md"}
  - {title: "My Notes", file: "My Notes.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, url: "mailto:nhado401@gmail.com"}
  - {title: LinkedIn, url: "https://www.linkedin.com/in/nhado401/"}
  - {title: Github, url: "https://github.com/nhado401"}
  - {title: "Blog", url: "https://nhavtdo.wordpress.com/"} 

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
