title: "Hello World!"
author: "Nha Do"
description: "University of California, Los Angeles (UCLA)"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "My CV", file: "/MyCV.pdf"}
  - {title: "Work Experience"}
  - {title: "Research Experience"}
  - {title: "Personal Blog", url: "https://nhavtdo.wordpress.com/"} 

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:nhado401@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/nhado401"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
